### ISSUE TITLE
unnecessary let binding clippy lint sometimes

### ISSUE THREAD

**Issue by Madoshakalaka** [its-the-shrimp/yew-html-ext#11]
```toml
[dependencies]
yew = { version="0.21", features=["csr"] }
yew-html-ext = "0.3.0"
```

# OK

```rs
html!{
  <input disabled=true/>
}
let disabled = true;
html!{
  <input disabled={disabled}/>
}
html!{
  <input placeholder="my placeholder"/>
}
```

# Not OK

```rs
let placeholder = "Disabled input";
html! {
    <input placeholder={placeholder} />
}
html! {
    <input disabled=true placeholder={placeholder}/>
}
let placeholder = "Disabled input";
html! {
    <input disabled=true {placeholder} />
}
```
